markdown: rdiscount
safe: true
lsi: false
pygments: true
# When running jekyll on your local computer change the base url to point to
# the _site directory (full-path)
baseurl: http://inesc-id-esw.github.io/jwormbench
